name: TheBridge
version: '${project.version}'
main: com.maanraj514.BridgePlugin
api-version: '1.20'
depend:
  - SlimeWorldManager
commands:
  setup:
    usage: /setup
    description: Setup the a game